headers = ["GAME_ID",
           "EVENTNUM",
           "EVENTMSGTYPE",
           "EVENTMSGACTIONTYPE",
           "PERIOD",
           "WCTIMESTRING",
           "PCTIMESTRING",
           "HOMEDESCRIPTION",
           "NEUTRALDESCRIPTION",
           "VISITORDESCRIPTION",
           "SCORE",
           "SCOREMARGIN",
           "PERSON1TYPE",
           "PLAYER1_ID",
           "PLAYER1_NAME",
           "PLAYER1_TEAM_ID",
           "PLAYER1_TEAM_CITY",
           "PLAYER1_TEAM_NICKNAME",
           "PLAYER1_TEAM_ABBREVIATION",
           "PERSON2TYPE",
           "PLAYER2_ID",
           "PLAYER2_NAME",
           "PLAYER2_TEAM_ID",
           "PLAYER2_TEAM_CITY",
           "PLAYER2_TEAM_NICKNAME",
           "PLAYER2_TEAM_ABBREVIATION",
           "PERSON3TYPE",
           "PLAYER3_ID",
           "PLAYER3_NAME",
           "PLAYER3_TEAM_ID",
           "PLAYER3_TEAM_CITY",
           "PLAYER3_TEAM_NICKNAME",
           "PLAYER3_TEAM_ABBREVIATION"]


event_dict = {1 : 'shot_made',
              2 : 'shot_missed',
              3 : 'free_throw',
              4 : 'rebound',
              5 : 'turnover',
              6 : 'foul1',
              7 : 'foul2',
              8 : 'sub',
              9 : 'timeout',
              10: 'jump_ball',
              11: 'unused',
              12: 'quarter_start',
              13: 'quarter_end',
              14: 'unused',
              15: 'unused',
              16: 'unused',
              17: 'unused',
              18: 'UNKNOWN'}

shot_desc =  {1 : 'jump shot',
              5 : 'layup',
              3 : 'hook shot',
              7 : 'dunk',
              40 : 'layup',
              41 : 'running layup',
              42 : 'driving layup',
              43 : 'alley oop layup',
              44 : 'reverse layup',
              45 : 'jump shot',
              46 : 'running jump shot',
              47 : 'turnaround jump shot',
              49 : 'driving dunk',
              50 : 'running dunk',
              52 : 'alley oop dunk',
              57 : 'hook shot',
              58 : 'turnaround hook shot',
              63 : 'fadeaway jumper',
              66 : 'jump bank shot',
              67 : 'hook bank shot',
              71 : 'finger roll layup',
              72 : 'putback layup',
              73 : 'driving reverse layup',
              74 : 'running reverse layup',
              75 : 'driving finger roll layup',
              76 : 'running finger roll layup',
              78 : 'floating jump shot',
              79 : 'pullup jump shot',
              80 : 'step back jump shot',
              81 : 'pullup bank shot',
              82 : 'driving bank shot',
              83 : 'fadeaway bank shot',
              85 : 'turnaround bank shot',
              86 : 'turnaround fadeaway shot',
              87 : 'putback dunk',
              96 : 'turnaround bank hook shot',
              97 : 'tip layup shot',
              98 : 'cutting layup',
              99 : 'cutting finger roll layup shot',
              100 : 'running alley oop layup shot',
              101 : 'driving floating jump shot',
              102 : 'driving floating bank jump shot',
              103 : 'running pull up jumper',
              104 : 'step bank bank jump shot',
              105 : 'turnaround fadeaway bank jump shot',
              106 : 'running alley oop dunk shot',
              107 : 'tip dunk shot',
              108 : 'cutting dunk shot'}

turnover_desc = {1 : 'bad pass',
                 2 : 'lost ball',
                 4 : 'travel',
                 5 : 'foul',
                 8 : '3 sec violation',
                 11 : 'shot clock violation',
                 15 : 'offensive goaltending',
                 17 : 'lane violation',
                 18 : 'jump ball violation',
                 19 : 'kicked ball violation',
                 20 : 'illegal assit',
                 21 : 'palming',
                 39 : 'step out of bounds',
                 40 : 'out of bounts lost ball',
                 41 : 'poss lost ball',
                 45 : 'out of bounds bad pass'}

event_desc = {'shot_made' : shot_desc,
              'shot_missed' : shot_desc,
              'free_throw' : {10 : '1 of 1',
                              11 : '1 of 2',
                              12 : '2 of 2',
                              13 : '1 of 3',
                              14 : '2 of 3',
                              15 : '3 of 3',
                              16 : 'technical'},
              'rebound' : {0 : 'player',
                           1 : 'team'},
              'turnover' : turnover_desc,
              'foul1' : {1 : 'personal foul',
                         2 : 's foul',
                         3 : 'l b foul',
                         4 : 'off foul',
                         6 : 'away from play foul',
                         11 : 'technical foul',
                         17 : 'defensive 3 sec',
                         26 : 'offensive charge foul',
                         27 : 'personal block foul',
                         28 : 'personal take foul',
                         29 : 'shooting block foul'},
              'foul2' : {1 : 'delay of game',
                         2 : 'defensive goaltending',
                         4 : 'jump ball',
                         5 : 'kicked ball'},
              'sub' : {0 : 'sub'},
              'timeout' : {1 : 'timeout',
                           2 : 'timeout - short',
                           4 : 'TV timeout?'},
              'jump_ball' : {0 : 'jump ball'},
              'quarter_start' : {0 : 'quarter start'},
              'quarter_end' : {0 : 'quarter end'},
              'unused' : {0 : '?'},
              'UNKNOWN' : {0 : '?', 1 : '?'}}
